export const toursList = [
    {

        title: "Desert Safari, Camel Ride & Al Khamya Camp",
        duration: "4 - 7 hours",
        rating: 4.5,
        reviews: "6,202",
        priceFrom: 35.44,
        image: "/tours/dubai1.jpg",
    },
    {
        title: "Safari, Quad Bike, Camel Ride & Buffet Dinner",
        duration: "7 hours",
        rating: 4.5,
        reviews: "2,425",
        priceFrom: 52.96,
        image: "/tours/dubai2.jpg",
    },
    {
        title: "Safari, Quad Bike & Sandboarding",
        duration: "5 hours",
        rating: 4,
        reviews: "1,002",
        priceFrom: 34.21,
        image: "/tours/dubai3.jpg",
    },
    {
        title: "Desert Quad Bike , Sand Surf , BBQ",
        duration: "6 hours",
        rating: 3.5,
        reviews: "87",
        priceFrom: 28.98,
        image: "/tours/dubai4.jpg",
    },
    {
        title: "Red Dune Safari, Camel Riding",
        duration: "5 - 8 hours",
        rating: 4.5,
        reviews: "14,548",
        priceFrom: 31.98,
        image: "/tours/dubai5.jpg",
    },
    {
        title: "Half Day Desert & Quad Bike Option",
        duration: "4 hours",
        rating: 5,
        reviews: "5,580",
        priceFrom: 25.98,
        image: "/tours/dubai6.jpg",
    },
    {
        title: "Evening Red Dunes With Buffer Dinner",
        duration: "7 hours",
        rating: 4.5,
        reviews: "785",
        priceFrom: 53.32,
        image: "/tours/dubai7.jpg",
    },
    {
        title: "Premium Red Dunes, Camel Safari , BBQ",
        duration: "7 hours",
        rating: 4.5,
        reviews: "8,412",
        priceFrom: 41.96,
        image: "/tours/dubai8.jpg",
    },
    {
        title: "Desert Safari With VIP BBQ and Optional Quad Bike",
        duration: "10 - 14 hours",
        rating: 5,
        reviews: "21,541",
        priceFrom: 78.90,
        image: "/tours/dubai9.jpg",
    },
    {
        title: "Evening Desert With Live Song",
        duration: "4 - 6 hours",
        rating: 4,
        reviews: "8,412",
        priceFrom: 35.98,
        image: "/tours/dubai10.jpg",
    },
    {
        title: "Desert Safari, Sand Boarding & Camp BBQ",
        duration: "4 - 6 hours",
        rating: 3,
        reviews: "5,751",
        priceFrom: 38.26,
        image: "/tours/dubai11.jpg",
    },
    {
        title: "Adventure Red Dune Desert Safari",
        duration: "4 - 7 hours",
        rating: 4.5,
        reviews: "6,301",
        priceFrom: 41.44,
        image: "/tours/dubai12.jpg",
    },
    {
        title: "Red Dune Desert Morning Adventure with Sand Boarding",
        duration: "3 - 4 hours",
        rating: 4.8,
        reviews: "4,412",
        priceFrom: 31.44,
        image: "/tours/dubai13.jpg",
    },
    {
        title: "Desert Day Trip with Camel Ride, Dancers & BBQ",
        duration: "6 hours",
        rating: 5,
        reviews: "925",
        priceFrom: 92.27,
        image: "/tours/dubai14.jpg",
    },
    {
        title: "SandBoarding & BBQ with View of Sunset",
        duration: "5 hours",
        rating: 4,
        reviews: "7,772",
        priceFrom: 44.21,
        image: "/tours/dubai15.jpg",
    },
    {
        title: "Evening Dune Buggy and Desert Adventure",
        duration: "4 - 6 hours",
        rating: 4.6,
        reviews: "15,879",
        priceFrom: 44.98,
        image: "/tours/dubai16.jpg",
    },
    {
        title: "Morning ATV Adventure",
        duration: "1 - 6 hours",
        rating: 4.8,
        reviews: "6,245",
        priceFrom: 21.98,
        image: "/tours/dubai17.jpg",
    },
    {
        title: "Sunrise Desert Jeep Safari with Wildlife",
        duration: "4 hours",
        rating: 4.1,
        reviews: "12,102",
        priceFrom: 18.21,
        image: "/tours/dubai18.jpg",
    },
    {
        title: "Arabian Dune Safari",
        duration: "5 hours",
        rating: 4.4,
        reviews: "1,233",
        priceFrom: 48.00,
        image: "/tours/dubai19.jpg",
    },
    {
        title: "Camel Safari with Overnight Camp",
        duration: "17 hours",
        rating: 5,
        reviews: "6,870",
        priceFrom: 161.12,
        image: "/tours/dubai20.jpg",
    },
    {
        title: "Morning Safari by Vintage Car",
        duration: "4 - 5 hours",
        rating: 3.9,
        reviews: "32",
        priceFrom: 78.90,
        image: "/tours/dubai21.jpg",
    },
    {
        title: "Desert Safari, BBQ",
        duration: "6 hours",
        rating: 4.1,
        reviews: "2,987",
        priceFrom: 31.98,
        image: "/tours/dubai22.jpg",
    },
    {
        title: "Hot Air Baloon Tour Over the Dubai Desert",
        duration: "4 hours",
        rating: 4.5,
        reviews: "7,751",
        priceFrom: 321.26,
        image: "/tours/dubai23.jpg",
    },
    {
        title: "Desert Safari with Burj Khalifa",
        duration: "7 hours",
        rating: 4.6,
        reviews: "17,301",
        priceFrom: 58.44,
        image: "/tours/dubai24.jpg",
    },
    {
        title: "test 1",
        duration: "1 hours",
        rating: 4.6,
        reviews: "17,301",
        priceFrom: 58.44,
        image: "/tours/dubai24.jpg",
    },
    {
        title: "test 2",
        duration: "1 hours",
        rating: 4.6,
        reviews: "17,301",
        priceFrom: 58.44,
        image: "/tours/dubai24.jpg",
    },
]